### ISSUE TITLE
Slack notifier missing 'url' value

### ISSUE THREAD

**Issue by CarlosEspejo** [mperham/inspeqtor-pro#3]
When I configure slack as the default alert channel 

```
send alerts
  via slack with team example, token example-token
```

**Comment by mperham** [comment]
The docs are out of date.  When you create a webhook integration Slack should give you a unique url.  You just need to put that in your config:

```
send alerts via slack with url <URL>
```

Let me know if that works and I'll update the wiki.  If Slack has changed how things work, let me know and we'll figure it out.

**Comment by CarlosEspejo** [comment]
Mike, it works great!!!

Thanks
