### ISSUE TITLE
Inspeqtor not monitoring multiple sidekiq instances

### ISSUE THREAD

**Issue by CarlosEspejo** [mperham/inspeqtor-pro#4]
I am trying to monitor 4 instances of sidekiq for high memory usage but Inspeqtor doesn't alert when the memory for one goes over 1GB. It does alert if you do `sudo stop sidekiq-workers.`

sidekiq-workers.inq

``` bash
check service sidekiq-workers
    if memory:rss > 1g then alert
```

sidekiq.conf

``` bash

# Save this config as /etc/init/sidekiq.conf then manage sidekiq with:
#   sudo start sidekiq index=0
#   sudo stop sidekiq index=0
#   sudo status sidekiq index=0
#
# Hack Upstart's reload command to 'quiet' Sidekiq:
#
#   sudo reload sidekiq index=0
#
# or use the service command:
#   sudo service sidekiq {start,stop,restart,status}
#

description "Sidekiq Background Worker"

# This script is not meant to start on bootup, workers.conf
# will start all sidekiq instances explicitly when it starts.
#start on runlevel [2345]
#stop on runlevel [06]

normal exit 0 TERM
reload signal USR1

instance $index


setuid deployer
chdir /home/deployer/apps/example_app/current

env RAILS_ENV=staging
env LANG=en_US.UTF-8
env LC_ALL=en_US.UTF-8


respawn
respawn limit 3 30


script
  . /etc/environment
  export REDIS_URL
  export DATABASE_HOST
  export DATABASE_PASSWORD
  export RAILS_ENV

  exec /home/deployer/.rbenv/shims/bundle exec "sidekiq -i ${index} -e staging -c 10 -q mailers -q new_user_invitation -q password_reset -q export"
end script
```

sidekiq-workers.conf

``` bash
# /etc/init/sidekiq-workers.conf - manage a set of Sidekiqs

# This example config should work with Ubuntu 12.04+.  It
# allows you to manage multiple Sidekiq instances with
# Upstart, Ubuntu's native service management tool.
#
# See sidekiq.conf for how to manage a single Sidekiq instance.
#
# Use "stop sidekiq-workers" to stop all Sidekiq instances.
# Use "start sidekiq-workers" to start all instances.
# Use "restart workers" to restart all instances.
# Crazy, right?
#

description "manages the set of sidekiq processes"

# This starts upon bootup and stops on shutdown
start on runlevel [2345]
stop on runlevel [06]

# Set this to the number of Sidekiq processes you want
# to run on this machine
env NUM_WORKERS=4

pre-start script
  for i in `seq 1 ${NUM_WORKERS}`
  do
    start sidekiq index=$i
  done
end script

post-stop script
  for i in `seq 1 ${NUM_WORKERS}`
  do
    stop sidekiq index=$i
  done
end script
```

**Comment by sorentwo** [comment]
You'll need to use `total_rss` instead. Your worker configuration is spawning 4 child processes, but the `rss` is only tracking the memory usage of parent process. Here is the relevant part from the wiki:

> The total_\* metrics include all child processes. This is useful for forking servers like Apache or Unicorn where the parent coordinator process doesn't do much and you want to monitor the child processes for memory leaks/bloat or unexpected CPU spikes.

See https://github.com/mperham/inspeqtor/wiki/Metrics#per-process for more details.

**Comment by mperham** [comment]
To follow up on what @sorentwo said, Inspeqtor only has two options for memory monitoring:
1. Monitor a single process with memory:rss.  Restart it if the rss goes over.
2. Monitor an entire set of processes with memory:total_rss.  Restart the entire set if the total_rss goes over.

Notably, Inspeqtor does not support Upstart service instances (the index=0 part) and can't restart a single child.  If you want to monitor a cluster of Sidekiq processes individually, you have a couple of options:
1. Create distinct Upstart .confs for each one: sidekiq0, sidekiq1, sidekiq2, etc.  Monitor each with memory:rss.
2. [Sidekiq Enterprise's multi-process mode](https://github.com/mperham/sidekiq/wiki/Ent-Multi-Process#memory-monitoring) can monitor and restart bloated children.  It allows you to have a single Upstart service which spawns N children; the parent monitors its children's memory and knows how to restart each.

**Comment by CarlosEspejo** [comment]
Your right, I am not having any luck with memory:total_rss but i'll try your other solutions. 

Thanks 😄
